--- #YAML:1.0
name:                chklinks
version:             3.05
abstract:            A non-threaded perl link checker
license:             gpl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    HTML::LinkExtor:               0
    HTTP::Cookies:                 0
    HTTP::Request:                 0
    LWP::RobotUA:                  0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - imacat <imacat@mail.imacat.idv.tw>
